name: Mr_Urfaneck
main: org.frminecraft.xeninscription.XenInscription
version: 1.0
commands:
   register:
      description: Register the user on the forums
      usage: /<command> <email>
      permission: XenInscription.command
      permission-message: Il manque la permission <permission>
